language: python
cache: pip
dist: xenial

services:
  - postgresql

before_script: createdb tree_test

matrix:
    fast_finish: true
    include:

      - { python: "3.6", env: DJANGO=2.2 }
      - { python: "3.6", env: DJANGO=3.0 }
      - { python: "3.6", env: DJANGO=master }

      - { python: "3.7", env: DJANGO=2.2 }
      - { python: "3.7", env: DJANGO=3.0 }
      - { python: "3.7", env: DJANGO=master }

      - { python: "3.8", env: DJANGO=3.0 }
      - { python: "3.8", env: DJANGO=master }

      - { python: "3.8", env: TOXENV=lint }

      - python: "3.8"
        env: TOXENV=dist
        script:
          - python setup.py bdist_wheel
          - rm -r django_tree.egg-info
          - tox --installpkg ./dist/django_tree-*.whl
          - tox

    allow_failures:
      - env: DJANGO=master

install:
    - pip install tox tox-venv tox-travis

script:
    - tox

notifications:
    email: false
